/* ════════════════════════════════════════════════════════
   LIGHTS OUT
   - Boards generated by random taps from all-off, so every
     board is guaranteed solvable.
   - Hint uses a GF(2) linear solver to show a real next tap
     on the shortest "toggle set" solution.
   ════════════════════════════════════════════════════════ */

/* ─── Safe storage shim ─── */
(function () {
  try { const t="__ls__"; localStorage.setItem(t,"1"); localStorage.removeItem(t); }
  catch (e) {
    let m={}; const safe={getItem:k=>k in m?m[k]:null,setItem:(k,v)=>m[k]=String(v),
      removeItem:k=>delete m[k],clear:()=>m={},key:i=>Object.keys(m)[i]||null,get length(){return Object.keys(m).length;}};
    try { Object.defineProperty(window,"localStorage",{value:safe,configurable:true}); } catch(e2){ window.localStorage=safe; }
  }
})();

// Each level: grid size N. Difficulty grows with size + scramble taps.
const LEVELS = [
  { n:3, scramble:4 },
  { n:3, scramble:6 },
  { n:4, scramble:6 },
  { n:4, scramble:9 },
  { n:5, scramble:8 },
  { n:5, scramble:12 },
  { n:5, scramble:16 },
  { n:6, scramble:14 },
  { n:6, scramble:20 },
  { n:7, scramble:24 },
];

const $ = id => document.getElementById(id);
const boardEl   = $('board');
const levelEl   = $('level-display');
const movesEl   = $('moves-display');
const litEl     = $('lit-display');
const bestEl    = $('best-display');
const winBanner = $('win-banner');
const winSub    = $('win-sub');
const btnNext   = $('btn-next');
const btnHint   = $('btn-hint');
const btnNew    = $('btn-new');

let state = {
  level: 0, n: 3, grid: [], moves: 0, won: false,
  cursor: { r: 0, c: 0 },
  bests: JSON.parse(localStorage.getItem('lo_bests') || 'null') || new Array(LEVELS.length).fill(null),
  hintCell: null,
};

/* ── Audio ── */
let audioCtx = null;
function tone(freq, type='sine', dur=0.08, vol=0.06, freqEnd) {
  try {
    if (!audioCtx) audioCtx = new (window.AudioContext||window.webkitAudioContext)();
    const o=audioCtx.createOscillator(), g=audioCtx.createGain();
    o.connect(g); g.connect(audioCtx.destination); o.type=type;
    o.frequency.setValueAtTime(freq, audioCtx.currentTime);
    if (freqEnd) o.frequency.exponentialRampToValueAtTime(freqEnd, audioCtx.currentTime+dur);
    g.gain.setValueAtTime(vol, audioCtx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime+dur);
    o.start(); o.stop(audioCtx.currentTime+dur);
  } catch(_){}
}
const Sfx = {
  on:  () => tone(520,'triangle',0.07,0.06,640),
  off: () => tone(300,'sine',0.07,0.05,220),
  win: () => [440,554,659,880].forEach((f,i)=>setTimeout(()=>tone(f,'triangle',0.4,0.09),i*110)),
  bad: () => tone(150,'sawtooth',0.12,0.05,110),
};

/* ── Grid helpers ── */
function idx(r,c,n){ return r*n+c; }
function inBounds(r,c,n){ return r>=0 && r<n && c>=0 && c<n; }

function applyTap(grid, r, c, n) {
  for (const [dr,dc] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]) {
    const nr=r+dr, nc=c+dc;
    if (inBounds(nr,nc,n)) grid[idx(nr,nc,n)] ^= 1;
  }
}

function countLit(grid) { return grid.reduce((a,v)=>a+v,0); }

/* ── Generate a solvable board (random taps from all-off) ── */
function generateBoard(n, scramble) {
  const grid = new Array(n*n).fill(0);
  const tapped = new Set();
  let applied = 0, guard = 0;
  while (applied < scramble && guard++ < scramble*8) {
    const r = Math.floor(Math.random()*n), c = Math.floor(Math.random()*n);
    const key = r*n+c;
    // avoid tapping the same cell twice (a double tap cancels out)
    if (tapped.has(key)) continue;
    tapped.add(key);
    applyTap(grid, r, c, n);
    applied++;
  }
  // Ensure not already solved
  if (countLit(grid) === 0) applyTap(grid, 0, 0, n);
  return grid;
}

/* ════════════════════════════════════════════════════════
   GF(2) SOLVER — find a toggle set that clears the board.
   Builds the NxN toggle matrix, solves A x = b (mod 2) with
   Gaussian elimination, returns which cells to tap. Used for
   hints: any un-tapped cell in the solution set is a valid hint.
   ════════════════════════════════════════════════════════ */
function solveToggles(grid, n) {
  const size = n*n;
  // Build augmented matrix rows as bitsets (arrays of 0/1) length size+1
  const A = [];
  for (let cell = 0; cell < size; cell++) {
    const row = new Array(size+1).fill(0);
    const r = Math.floor(cell/n), c = cell%n;
    for (const [dr,dc] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]) {
      const nr=r+dr, nc=c+dc;
      if (inBounds(nr,nc,n)) row[idx(nr,nc,n)] = 1;
    }
    row[size] = grid[cell]; // b = current lit state (we want to turn all off)
    A.push(row);
  }
  // Gaussian elimination over GF(2)
  const where = new Array(size).fill(-1);
  let row = 0;
  for (let col = 0; col < size && row < size; col++) {
    let sel = -1;
    for (let i = row; i < size; i++) if (A[i][col]) { sel = i; break; }
    if (sel === -1) continue;
    [A[sel], A[row]] = [A[row], A[sel]];
    where[col] = row;
    for (let i = 0; i < size; i++) {
      if (i !== row && A[i][col]) {
        for (let j = col; j <= size; j++) A[i][j] ^= A[row][j];
      }
    }
    row++;
  }
  // Extract a solution (free vars = 0)
  const x = new Array(size).fill(0);
  for (let col = 0; col < size; col++) {
    if (where[col] !== -1) x[col] = A[where[col]][size];
  }
  return x; // array of 0/1, 1 = tap this cell
}

/* ── Render ── */
function render(opts={}) {
  const n = state.n;
  boardEl.style.gridTemplateColumns = `repeat(${n}, 1fr)`;
  // Size cells so the board fits nicely
  const maxBoard = Math.min(440, window.innerWidth - 60);
  boardEl.style.width = maxBoard + 'px';

  if (opts.rebuild !== false) {
    boardEl.innerHTML = '';
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        const cell = document.createElement('div');
        cell.className = 'cell' + (state.grid[idx(r,c,n)] ? ' on' : '');
        if (state.cursor.r===r && state.cursor.c===c) cell.classList.add('cursor');
        if (state.hintCell && state.hintCell[0]===r && state.hintCell[1]===c) cell.classList.add('hint');
        cell.dataset.r = r; cell.dataset.c = c;
        cell.addEventListener('click', () => tap(r, c));
        boardEl.appendChild(cell);
      }
    }
  }

  levelEl.textContent = state.level + 1;
  movesEl.textContent = state.moves;
  litEl.textContent = countLit(state.grid);
  const best = state.bests[state.level];
  bestEl.textContent = best !== null ? best : '—';
}

function bump(el){ el.classList.remove('bump'); void el.offsetWidth; el.classList.add('bump'); }

function getCellEl(r,c){ return boardEl.querySelector(`[data-r="${r}"][data-c="${c}"]`); }

/* ── Tap a cell ── */
function tap(r, c) {
  if (state.won) return;
  const n = state.n;
  clearHint();

  applyTap(state.grid, r, c, n);
  state.moves++;
  bump(movesEl);

  // animate the affected cells
  for (const [dr,dc] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]) {
    const nr=r+dr, nc=c+dc;
    if (inBounds(nr,nc,n)) {
      const el = getCellEl(nr,nc);
      if (el) {
        el.classList.toggle('on', !!state.grid[idx(nr,nc,n)]);
        el.classList.remove('flip'); void el.offsetWidth; el.classList.add('flip');
      }
    }
  }
  // keep cursor marker in sync
  render({rebuild:false});
  refreshMarkers();

  const lit = countLit(state.grid);
  litEl.textContent = lit;
  if (state.grid[idx(r,c,n)]) Sfx.on(); else Sfx.off();

  if (lit === 0) win();
}

function refreshMarkers() {
  boardEl.querySelectorAll('.cell').forEach(el => el.classList.remove('cursor'));
  const cel = getCellEl(state.cursor.r, state.cursor.c);
  if (cel) cel.classList.add('cursor');
}

function win() {
  state.won = true;
  Sfx.win();
  const best = state.bests[state.level];
  if (best === null || state.moves < best) {
    state.bests[state.level] = state.moves;
    localStorage.setItem('lo_bests', JSON.stringify(state.bests));
    bump(bestEl);
  }
  bestEl.textContent = state.bests[state.level];
  winSub.textContent = `Solved in ${state.moves} move${state.moves===1?'':'s'}`;
  btnNext.style.display = state.level < LEVELS.length-1 ? '' : 'none';
  winBanner.classList.add('show');
  render({rebuild:false});
}

/* ── Hint ── */
function showHint() {
  if (state.won) return;
  clearHint();
  const n = state.n;
  const sol = solveToggles(state.grid.slice(), n);
  // pick any cell in the solution set (a valid next tap)
  let picked = null;
  for (let i = 0; i < sol.length; i++) {
    if (sol[i]) { picked = [Math.floor(i/n), i%n]; break; }
  }
  if (!picked) {
    // already solved or unusual; nudge with a safe tap that reduces lit
    Sfx.bad();
    return;
  }
  state.hintCell = picked;
  const el = getCellEl(picked[0], picked[1]);
  if (el) el.classList.add('hint');
  tone(600,'sine',0.09,0.05,720);
  setTimeout(clearHint, 2500);
}
function clearHint() {
  state.hintCell = null;
  boardEl.querySelectorAll('.hint').forEach(el => el.classList.remove('hint'));
}

/* ── Level flow ── */
function startLevel(li) {
  state.level = li;
  const { n, scramble } = LEVELS[li];
  state.n = n;
  state.grid = generateBoard(n, scramble);
  state.moves = 0;
  state.won = false;
  state.cursor = { r: 0, c: 0 };
  clearHint();
  winBanner.classList.remove('show');
  render({rebuild:true});
}

/* ── Controls ── */
btnNext.addEventListener('click', () => {
  if (state.level < LEVELS.length-1) startLevel(state.level+1);
});
btnHint.addEventListener('click', showHint);
btnNew.addEventListener('click', () => startLevel(state.level));

/* ── Keyboard ── */
window.addEventListener('keydown', (e) => {
  const n = state.n;
  if (e.key === 'ArrowUp')    { state.cursor.r = Math.max(0, state.cursor.r-1); refreshMarkers(); e.preventDefault(); }
  else if (e.key === 'ArrowDown')  { state.cursor.r = Math.min(n-1, state.cursor.r+1); refreshMarkers(); e.preventDefault(); }
  else if (e.key === 'ArrowLeft')  { state.cursor.c = Math.max(0, state.cursor.c-1); refreshMarkers(); e.preventDefault(); }
  else if (e.key === 'ArrowRight') { state.cursor.c = Math.min(n-1, state.cursor.c+1); refreshMarkers(); e.preventDefault(); }
  else if (e.key === ' ' || e.key === 'Enter') { tap(state.cursor.r, state.cursor.c); e.preventDefault(); }
  else if (e.key.toLowerCase() === 'h') { showHint(); }
  else if (e.key.toLowerCase() === 'n') { startLevel(state.level); }
});

window.addEventListener('resize', () => render({rebuild:false}));

/* ── Boot ── */
startLevel(0);
